ColorLongLife/Areas/admin/Controllers/ConsultationSettingsAdminController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using ColorLongLife.Areas.admin.Models.ConsultationSettings;
using ColorLongLife.DataAccessLayer.Models;

namespace ColorLongLife.Areas.admin.Controllers
{
    public class ConsultationSettingsAdminController : BaseAdminController
    {
        #region Default settings

        private readonly TimeSpan DefaultConsultationsStartTime = new TimeSpan(9, 0, 0);
        private readonly TimeSpan DefaultConsultationsEndTime = new TimeSpan(18, 0, 0);
        private readonly TimeSpan DefaultConsultationDuration = new TimeSpan(0, 30, 0);
        private readonly TimeSpan DefaultRest = new TimeSpan(0, 30, 0);

        private readonly SelectList DefaultConsultationDurationList = new SelectList(new List<TimeSpan>
        {
            new TimeSpan(0, 15, 0),
            new TimeSpan(0, 30, 0),
            new TimeSpan(0, 45, 0)
        });

        private readonly SelectList DefaultRestDurationList = new SelectList(new List<TimeSpan>
        {
            new TimeSpan(0, 15, 0),
            new TimeSpan(0, 30, 0),
            new TimeSpan(0, 45, 0)
        });

        private readonly SelectList ApplyForList = new SelectList(new List<Int32> { 7, 30 });

        #endregion

        [HttpGet]
        public ActionResult Index(DateTime? startDate)
        {
            IndexModel model = new IndexModel();
            DateTime compareDate = startDate ?? DateTime.UtcNow.Date;
            List<ConsultationSettingsModel> settings =
                this.UnitOfWork.ConsultationsSettingsRepository.Get(x => DbFunctions.TruncateTime(x.Date) >= compareDate).Select(x => new ConsultationSettingsModel
                {
                    ConsultationSettingsId = x.ConsultationSettingsId,
                    Date = x.Date,
                    StartTime = x.StartTime,
                    EndTime = x.EndTime,
                    TimeslotDuration = x.TimeslotDuration,
                    RestDuration = x.RestDuration,
                    IsActive = x.IsActive
                }).ToList();
            model.ConsultationSettings = settings;

            return View(model);
        }

        [HttpGet]
        public ActionResult Create()
        {
            ConsultationSettingsModel model = new ConsultationSettingsModel
            {
                Date = DateTime.UtcNow.Date,
                StartTime = this.DefaultConsultationsStartTime,
                EndTime = this.DefaultConsultationsEndTime,
                TimeslotDuration = this.DefaultConsultationDuration,
                RestDuration = this.DefaultRest,
                ApplyFor = 7
            };

            ViewBag.ConsultationDuration = this.DefaultConsultationDurationList;
            ViewBag.RestDuration = this.DefaultRestDurationList;
            ViewBag.ApplyForList = this.ApplyForList;

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(ConsultationSettingsModel model)
        {
            if (!ModelState.IsValid)
            {
                base.ShowErrorAlert("Ошибка", "Проверьте введенные данные");
                ViewBag.ConsultationDuration = this.DefaultConsultationDurationList;
                ViewBag.RestDuration = this.DefaultRestDurationList;
                ViewBag.ApplyForList = this.ApplyForList;
                return View(model);
            }

            DateTime startPeriod = model.Date;
            DateTime endPeriod = model.Date.AddDays(model.ApplyFor).Date;
            var existingSettings =
                this.UnitOfWork.ConsultationsSettingsRepository.Get(
                    x =>
                        DbFunctions.TruncateTime(x.Date) >= startPeriod && DbFunctions.TruncateTime(x.Date) <= endPeriod)
                    .ToList();

            List<ConsultationSettings> settingToInserts = new List<ConsultationSettings>();
            List<ConsultationSettings> settingsToUpdate = new List<ConsultationSettings>();
            for (int i = 0; i < model.ApplyFor; i++)
            {
                DateTime settingsDate = model.Date.AddDays(i).Date;
                if (existingSettings.Any(x => x.Date == settingsDate))
                {
                    ConsultationSettings existingSetting = existingSettings.First(x => x.Date == settingsDate);
                    existingSetting.StartTime = model.StartTime;
                    existingSetting.EndTime = model.EndTime;
                    existingSetting.TimeslotDuration = model.TimeslotDuration;
                    existingSetting.RestDuration = model.RestDuration;
                    settingsToUpdate.Add(existingSetting);
                }
                else
                {
                    settingToInserts.Add(new ConsultationSettings
                    {
                        Date = model.Date.AddDays(i),
                        StartTime = model.StartTime,
                        EndTime = model.EndTime,
                        TimeslotDuration = model.TimeslotDuration,
                        RestDuration = model.RestDuration,
                        IsActive = true
                    });
                }
            }

            this.UnitOfWork.ConsultationsSettingsRepository.InsertRange(settingToInserts);
            foreach (var entity in settingsToUpdate)
            {
                this.UnitOfWork.ConsultationsSettingsRepository.Update(entity);
            }
            await this.UnitOfWork.SaveAsync();

            base.ShowSuccessAlert("OK", "Данные успешно добавлены.");
            return RedirectToRoute("consultationsettings");
        }

        public async Task<ActionResult> Delete(Int32 settingsId)
        {
            if (settingsId < 0)
            {
                base.ShowErrorAlert("Ошибка", "Неверные данные.");
                return RedirectToRoute("consultationsettings");
            }

            ConsultationSettings consultationSettings =
                this.UnitOfWork.ConsultationsSettingsRepository.Get(x => x.ConsultationSettingsId.Equals(settingsId))
                    .FirstOrDefault();
            if (consultationSettings == null)
            {
                base.ShowErrorAlert("Ошибка", "Информация не найдена.");
                return RedirectToRoute("consultationsettings");
            }

            this.UnitOfWork.ConsultationsSettingsRepository.Delete(consultationSettings);
            await this.UnitOfWork.SaveAsync();

            base.ShowSuccessAlert("OK", "Данные успешно удалены.");
            return RedirectToRoute("consultationsettings");
        }
    }
}

ColorLongLife/Areas/admin/Views/ConsultationSettingsAdmin/Create.cshtml
@model ColorLongLife.Areas.admin.Models.ConsultationSettings.ConsultationSettingsModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/admin/Views/Shared/_CRUDLayout.cshtml";
}

@section styles{
    <link rel="stylesheet" href="@Url.Content("~/Areas/admin/plugins/timepicker/bootstrap-timepicker.css")">
}

@section scripts{
    <script type="text/javascript" src="@Url.Content("~/Areas/admin/plugins/timepicker/bootstrap-timepicker.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Areas/admin/plugins/datepicker/locales/bootstrap-datepicker.ru.js")"></script>
    <script type="text/javascript">
        $("#tbxDate").datepicker({
            format: "dd/mm/yyyy",
            language: "ru",
            autoclose: true,
            todayHighlight: true
        });

        $("#tbxStartTime, #tbxEndTime").timepicker({
            showMeridian: false,
            disableMousewheel: true
        });
    </script>
}

<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">Новые настройка консультаций</h3>
    </div>
    @using (Html.BeginForm("Create", "ConsultationSettingsAdmin", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary()
        <div class="box-body">
            <div class="form-group input-group">
                <label for="tbxDate">День консультаций</label>
                @Html.TextBoxFor(x => x.Date, "{0:dd/MM/yyyy}", new { id = "tbxDate", @class = "form-control", placeholder = "Дата консультаций" })
            </div>
            <div class="form-group input-group bootstrap-timepicker timepicker">
                <label for="tbxStartTime">Начало консультаций</label>
                @Html.TextBoxFor(x => x.StartTime, new { id = "tbxStartTime", @class = "form-control", placeholder = "Начало консультаций" })
            </div>
            <div class="form-group input-group bootstrap-timepicker timepicker">
                <label for="tbxEndTime">Начало консультаций</label>
                @Html.TextBoxFor(x => x.EndTime, new { id = "tbxEndTime", @class = "form-control", placeholder = "Окончание консультаций" })
            </div>
            <div class="form-group input-group bootstrap-timepicker timepicker">
                <label for="tbxEndTime">Продолжительность консультаций</label>
                @Html.DropDownListFor(x => x.TimeslotDuration, ViewBag.ConsultationDuration as SelectList, new { id = "ddlTimeslotDuration", @class = "form-control" })
            </div>
            <div class="form-group input-group bootstrap-timepicker timepicker">
                <label for="tbxEndTime">Отдых после консультаций</label>
                @Html.DropDownListFor(x => x.RestDuration, ViewBag.RestDuration as SelectList, new { id = "ddlRestDuration", @class = "form-control" })
            </div>
            <div class="form-group input-group bootstrap-timepicker timepicker">
                <label for="ddlApplyFor">Применить на:</label>
                @Html.DropDownListFor(x => x.ApplyFor, ViewBag.ApplyForList as SelectList, new { id = "ddlApplyFor", @class = "form-control" })
            </div>
        </div>
        <div class="box-footer">
            <button class="btn btn-success" type="submit">Сохранить</button>
            <a class="btn btn-link" href="/admin/database/consultationsettings">Назад</a>
        </div>
    }
</div>

ColorLongLife/Areas/admin/Views/ConsultationSettingsAdmin/Index.cshtml
@using GridMvc.Html
@model ColorLongLife.Areas.admin.Models.ConsultationSettings.IndexModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/admin/Views/Shared/_CRUDLayout.cshtml";
}

@section styles{
    <link type="text/css" rel="stylesheet" href="@Url.Content("~/Content/Gridmvc.css")" />
}

@section scripts{
    <script type="text/javascript" src="@Url.Content("~/Scripts/gridmvc.js")"></script>
}

<h2>Настройки консультаций</h2>

<div>
    @Html.Grid(Model.ConsultationSettings).Columns(columns =>
    {
        columns.Add(x => x.Date, "Date")
            .Format("{0:dd/MM}")
            .Titled("Дата")
            .SetWidth("auto");
        columns.Add(x => x.StartTime, "StartTime")
            .Titled("Начало консультаций")
            .SetWidth("auto");
        columns.Add(x => x.EndTime, "EndTime")
            .Titled("Завершение консультаций")
            .SetWidth("auto");
        columns.Add(x => x.TimeslotDuration, "TimeslotDuration")
            .Titled("Продолжительность консультации")
            .SetWidth("auto");
        columns.Add(x => x.RestDuration, "RestDuration")
            .Titled("Продолжительность перерыва")
            .SetWidth("auto");
        columns.Add()
            .Encoded(false)
            .Sanitized(false)
            .SetWidth("auto")
            .RenderValueAs(x =>
            @<div class="btn-group">
                @Html.RouteLink("Редактировать", "consultationsettings_edit", new { settingsId = x.ConsultationSettingsId }, new { @class = "btn btn-primary btn-flat" })
                @Html.RouteLink("Удалить", "consultationsettings_delete", new { settingsId = x.ConsultationSettingsId }, new { @class = "btn btn-danger btn-flat" })
            </div>);
    })

    <a class="btn btn-link" href="@Url.RouteUrl("consultationsettings_create")">Создать</a>
</div>