ColorLongLife/Areas/admin/Controllers/CategoriesAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using ColorLongLife.Areas.admin.Models.Categories;
using ColorLongLife.DataAccessLayer.Models;

namespace ColorLongLife.Areas.admin.Controllers
{
    public class CategoriesAdminController : BaseAdminController
    {
        [HttpGet]
        public ActionResult Index()
        {
            IndexModel model = new IndexModel();
            model.Categories = this.UnitOfWork.CategoryRepository.Get()
                .OrderBy(x => x.Name)
                .Select(x => new CategoryModel
                {
                    CategoryId = x.IdCategory,
                    Name = x.Name,
                    Description = x.Description
                }).ToList();

            return View(model);
        }

        [HttpGet]
        public ActionResult Create()
        {
            CategoryModel model = new CategoryModel();

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CategoryModel model)
        {
            if (!ModelState.IsValid)
            {
                base.ShowErrorAlert("Ошибка", "Проверьте введенные данные!");
                return View(model);
            }

            Category existingCategory = this.UnitOfWork.CategoryRepository.Get(x => x.Name.Equals(model.Name)).FirstOrDefault();
            if (existingCategory != null)
            {
                base.ShowErrorAlert("Ошибка", "Такая категория уже есть!");
                return View(model);
            }

            Category category = new Category
            {
                Name = model.Name,
                Description = model.Description
            };
            this.UnitOfWork.CategoryRepository.Insert(category);
            await this.UnitOfWork.SaveAsync();

            base.ShowSuccessAlert("OK", "Категория успешно добавлена");
            return RedirectToRoute("categories");
        }

        [HttpGet]
        public async Task<ActionResult> Delete(Int32 categoryId)
        {
            Category category = this.UnitOfWork.CategoryRepository.Get(x => x.IdCategory.Equals(categoryId)).SingleOrDefault();
            if (category == null)
            {
                base.ShowErrorAlert("ERROR", "Категория не найдена!");
                return RedirectToRoute("categories");
            }

            this.UnitOfWork.CategoryRepository.Delete(category);
            await this.UnitOfWork.SaveAsync();
            base.ShowSuccessAlert("OK", "Категория успешно удалена!");

            return RedirectToRoute("categories");
        }

        [HttpGet]
        public ActionResult Edit(Int32 categoryId)
        {
            Category category = this.UnitOfWork.CategoryRepository.GetById(categoryId);
            if (category == null)
            {
                base.ShowErrorAlert("Ошибка", "Данные не найдены.");
                return RedirectToRoute("categories");
            }

            CategoryModel model = new CategoryModel
            {
                CategoryId = categoryId,
                Name = category.Name,
                Description = category.Description
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(CategoryModel model)
        {
            if (!this.ModelState.IsValid)
            {
                base.ShowErrorAlert("Косяк", "Проверьте введенные данные.");
                return View(model);
            }

            Category category = this.UnitOfWork.CategoryRepository.GetById(model.CategoryId);
            if (category == null)
            {
                base.ShowErrorAlert("Косяк", "Данные в базе не найдены.");
                return View(model);
            }

            category.Name = model.Name;
            category.Description = model.Description;
            this.UnitOfWork.CategoryRepository.Update(category);
            await this.UnitOfWork.SaveAsync();

            base.ShowSuccessAlert("Успех", "Данные успешно обновлены.");
            return View(model);
        }
    }
}

ColorLongLife/Areas/admin/Views/CategoriesAdmin/Create.cshtml
@model ColorLongLife.Areas.admin.Models.Categories.CategoryModel

@{
    ViewBag.Title = "Добавление новой категории";
    Layout = "~/Areas/admin/Views/Shared/_CRUDLayout.cshtml";
}

<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">Добавление новой должности</h3>
    </div>
    @using (Html.BeginForm("Create", "CategoriesAdmin", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary()
        <div class="box-body">
            <div class="form-group">
                <label for="tbxTitle">Категория</label>
                @Html.TextBoxFor(x => x.Name, new { id = "tbxTitle", @class = "form-control", placeholder = "Категория" })
            </div>
            <div class="form-group">
                <label for="tbxDescription">Описание</label>
                @Html.TextAreaFor(x => x.Description, new { id = "tbxDescription", @class = "form-control", placeholder = "Описание" })
            </div>
        </div>
        <div class="box-footer">
            <button class="btn btn-success" type="submit">Сохранить</button>
            <a class="btn btn-link" href="@Url.RouteUrl("categories")">Назад</a>
        </div>
    }
</div>

ColorLongLife/Areas/admin/Views/CategoriesAdmin/Edit.cshtml
@using System.Web.UI.WebControls
@model ColorLongLife.Areas.admin.Models.Categories.CategoryModel

@{
    ViewBag.Title = "Редактирование категории";
    Layout = "~/Areas/admin/Views/Shared/_CRUDLayout.cshtml";
}

<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">Редактирование категории</h3>
    </div>
    @using (Html.BeginForm("Edit", "CategoriesAdmin", FormMethod.Post, new {categoryId = Model.CategoryId}))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary()
        @Html.HiddenFor(x => x.CategoryId)

        <div class="box-body">
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new {@class = "control-label col-md-2"})
                @Html.EditorFor(model => model.Name, new {htmlAttributes = new {@class = "form-control", placeholder = "Категория" } })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new {@class = "control-label col-md-2"})
                @Html.EditorFor(model => model.Description, new {htmlAttributes = new {@class = "form-control", placeholder = "Описание" } })
            </div>
        </div>
        <div class="box-footer">
            <button class="btn btn-success" type="submit">Сохранить</button>
            <a class="btn btn-link" href="/admin/database/categories">Назад</a>
        </div>
    }
</div>

ColorLongLife/Areas/admin/Views/CategoriesAdmin/Index.cshtml
@using GridMvc.Html
@model ColorLongLife.Areas.admin.Models.Categories.IndexModel

@{
    ViewBag.Title = "Категории";
    Layout = "~/Areas/admin/Views/Shared/_CRUDLayout.cshtml";
}

<div>
    @Html.Grid(Model.Categories).Columns(columns =>
            {
                columns.Add(x => x.Name, "Category")
                    .Titled("Категория")
                    .SetWidth(400);
                columns.Add(x => x.Description, "Description")
                    .Titled("Описание");
                columns.Add()
                    .Encoded(false)
                    .Sanitized(false)
                    .SetWidth(250)
                    .RenderValueAs(x =>
                    @<div class="btn-group">
                        @Html.RouteLink("Редактировать", "categories_edit", new { categoryId = x.CategoryId }, new { @class = "btn btn-primary btn-flat" })
                        @Html.RouteLink("Удалить", "categories_delete", new { categoryId = x.CategoryId }, new { @class = "btn btn-danger btn-flat" })
                    </div>);
            })
</div>
<a class="btn btn-link" href="@Url.RouteUrl("categories_create")">Создать</a>