ColorLongLife/Areas/admin/Controllers/HappinessAdminController.cs
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using ColorLongLife.Areas.admin.Models.Happiness;
using ColorLongLife.DataAccessLayer.Models;
using IndexModel = ColorLongLife.Areas.admin.Models.Happiness.IndexModel;

namespace ColorLongLife.Areas.admin.Controllers
{
    public class HappinessAdminController : BaseAdminController
    {
        private const Int32 MaxUploadImageSize = 5242880;

        // GET: admin/HappinessAdmin
        public ActionResult Index()
        {
            IndexModel model = new IndexModel();
            model.HappinessList = this.UnitOfWork.HappinessRepository.Get().Select(x => new HappinessModel
            {
                HappinessId = x.HappinessId,
                Title = x.Title,
                Description = x.Description,
                PathToImage = x.PathToImage
            });

            return View(model);
        }

        [HttpGet]
        public ActionResult Create()
        {
            HappinessModel model = new HappinessModel();

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(HappinessModel happiness)
        {
            if (this.ModelState.IsValid)
            {
                var existingHappiness =
                    this.UnitOfWork.HappinessRepository.Get(x => x.Title.ToLower().Equals(happiness.Title))
                        .SingleOrDefault();
                if (existingHappiness != null)
                {
                    base.ShowErrorAlert("Дубликат", "Данная позиция уже существует!");
                    return this.View(happiness);
                }

                if (this.HttpContext.Request.Files.Count == 0 ||
                    this.HttpContext.Request.Files[0] == null ||
                    this.HttpContext.Request.Files[0].ContentLength == 0 ||
                    this.HttpContext.Request.Files[0].ContentLength > MaxUploadImageSize)
                {
                    base.ShowErrorAlert("Ошибка", "Вы не выбрали изображение счастья или файл превысил добустимый размер в 5Mb!");
                    return View(happiness);
                }
                string folder = HttpContext.ApplicationInstance.Server.MapPath(@"\Content\storage");
                string fileName = HttpContext.Request.Files[0].FileName;
                string path = Path.Combine(folder, fileName);
                HttpContext.Request.Files[0].SaveAs(path);

                Happiness dataHappiness = new Happiness
                {
                    Title = happiness.Title,
                    Description = happiness.Description,
                    PathToImage = Path.Combine("/Content/storage", fileName)
                };

                this.UnitOfWork.HappinessRepository.Insert(dataHappiness);
                await this.UnitOfWork.SaveAsync();

                base.ShowSuccessAlert("Успешно", "Новоя позиция создана.");
                return RedirectToRoute("happiness");
            }

            base.ShowErrorAlert("Input error", "Plase check input fields.");
            return this.View(happiness);
        }

        [HttpGet]
        public ActionResult Edit(Int32 happinessId)
        {
            Happiness happiness = this.UnitOfWork.HappinessRepository.GetById(happinessId);
            if (happiness == null)
            {
                base.ShowErrorAlert("Ошибка", "Данные не найдены.");
                return RedirectToRoute("happiness");
            }

            HappinessModel model = new HappinessModel
            {
                HappinessId = happinessId,
                Title = happiness.Title,
                Description = happiness.Description,
                PathToImage = happiness.PathToImage
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(HappinessModel model)
        {
            if (!this.ModelState.IsValid)
            {
                base.ShowErrorAlert("Косяк", "Проверьте введенные данные.");
                return View(model);
            }

            Happiness happiness = this.UnitOfWork.HappinessRepository.GetById(model.HappinessId);
            if (happiness == null)
            {
                base.ShowErrorAlert("Косяк", "Данные в базе не найдены.");
                return View(model);
            }

            happiness.Title = model.Title;
            happiness.Description = model.Description;
            this.UnitOfWork.HappinessRepository.Update(happiness);
            await this.UnitOfWork.SaveAsync();

            base.ShowSuccessAlert("Успех", "Данные успешно обновлены.");
            return View(model);
        }

        public async Task<ActionResult> Delete(Int32 happinessId)
        {
            Happiness happiness = this.UnitOfWork.HappinessRepository.GetById(happinessId);
            if (happiness == null)
            {
                base.ShowErrorAlert("Ошибка", "Данные не найдены.");
                return RedirectToRoute("happiness");
            }

            this.UnitOfWork.HappinessRepository.Delete(happiness);
            await this.UnitOfWork.SaveAsync();

            base.ShowSuccessAlert("Успех", "Данные успешно удалены.");
            return RedirectToRoute("happiness");
        }
    }
}

ColorLongLife/Areas/admin/Views/HappinessAdmin/Create.cshtml
@model ColorLongLife.Areas.admin.Models.Happiness.HappinessModel
@{
    ViewBag.Title = "Новое счастье";
    Layout = "~/Areas/admin/Views/Shared/_CRUDLayout.cshtml";
}

@section styles
{
    <link type="text/css" rel="stylesheet" href="@Url.Content("~/Areas/admin/plugins/fileupload/css/fileinput.min.css")" />
}

@section scripts{
    
    <script type="text/javascript" src="~/Areas/admin/plugins/fileupload/fileinput.min.js"></script>
    <script type="text/javascript" src="~/Areas/admin/plugins/fileupload/locale/fileinput_locale_ru.js"></script>
    <script type="text/javascript">
        $('#pathToImage').fileinput({
            showUpload: false,
            showCaption: true,
            allowedFileTypes: ['image'],
            allowedFileExtensions: ['jpg', 'png'],
            maxFileSize: 5120, // max file size is 5Mb
            maxFileCount: 1,
            msgInvalidFileExtension: 'Выбран неверный тип файла "{name}". Только "{extensions}" файлы разрешено загружать.',
            msgInvalidFileType: 'Выбран неверный тип файла "{name}". Только "{types}" файлы разрешено загружать.',
            msgSizeTooLarge: 'Файл "{name}" ({size} KB) превысил допустимый размер файла {maxSize} KB. Пожалуйста, выберите новый файл!'
        });
    </script>
}

<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">Добавление нового счастья</h3>
    </div>
    @using (Html.BeginForm("Create", "HappinessAdmin", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary()
        <div class="box-body">
            <div class="form-group">
                <label for="tbxTitle">Заголовок</label>
                @Html.TextBoxFor(x => x.Title, new { id = "tbxTitle", @class = "form-control", placeholder = "Мое счастье как..." })
            </div>
            <div class="form-group">
                <label for="tbxDescription">Описание</label>
                @Html.TextAreaFor(x => x.Description, new {id = "tbxDescription", @class = "form-control", placeholder = "Краткое описание"})
            </div>
            <div class="form-group">
                <label for="exampleInputFile">Изображение счастья</label>
                <input type="file" class="file" id="pathToImage" name="file">
            </div>
        </div>
        <div class="box-footer">
            <button class="btn btn-success" type="submit">Сохранить</button>
            <a class="btn btn-link" href="/admin/database/happiness">Назад</a>
        </div>
    }
</div>

ColorLongLife/Areas/admin/Views/HappinessAdmin/Edit.cshtml
@model ColorLongLife.Areas.admin.Models.Happiness.HappinessModel

@{
    ViewBag.Title = "Редактирование";
    Layout = "~/Areas/admin/Views/Shared/_CRUDLayout.cshtml";
}

<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">Редактирование счастья</h3>
    </div>
    @using (Html.BeginForm("Edit", "HappinessAdmin", FormMethod.Post, new { happinesId = Model.HappinessId }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary()
        @Html.HiddenFor(x => x.HappinessId)
        <div class="box-body">
            <div class="form-group">
                <label for="tbxTitle">Мое счастье как...</label>
                @Html.TextBoxFor(x => x.Title, new { id = "tbxTitle", @class = "form-control", placeholder = "Мое счастье как..." })
            </div>
            <div class="form-group">
                <label for="tbxDescription">Краткое описание</label>
                @Html.TextAreaFor(x => x.Description, new { id = "tbxDescription", @class = "form-control", placeholder = "Краткое описание" })
            </div>
        </div>
        <div class="box-footer">
            <button class="btn btn-success" type="submit">Сохранить</button>
            <a class="btn btn-link" href="/admin/database/happiness">Назад</a>
        </div>
    }
</div>

ColorLongLife/Areas/admin/Views/HappinessAdmin/Index.cshtml
@using GridMvc.Html
@model ColorLongLife.Areas.admin.Models.Happiness.IndexModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/admin/Views/Shared/_CRUDLayout.cshtml";
}

@section styles{
    <link type="text/css" rel="stylesheet" href="@Url.Content("~/Content/Gridmvc.css")" />
}

@section scripts{
    <script type="text/javascript" src="@Url.Content("~/Scripts/gridmvc.js")"></script>
}

<h2>Мое счастье как...</h2>

<div>
    @Html.Grid(Model.HappinessList).Columns(columns =>
    {
        columns.Add()
                    .Encoded(false)
                    .Sanitized(false)
                    .SetWidth(150)
                    .RenderValueAs(x =>
                    @<img alt="@($"{x.Title}")" src="@x.PathToImage" width="75" height="75" class="img-circle" />);
        columns.Add(x => x.Title, "Title").Titled("Мое счастье как...");
        columns.Add(x => x.Description, "Description").Titled("Описание");
        columns.Add()
            .Encoded(false)
            .Sanitized(false)
            .SetWidth(250)
            .RenderValueAs(x =>
            @<div class="btn-group">
                @Html.RouteLink("Редактировать", "happiness_edit", new { happinessId = x.HappinessId }, new { @class = "btn btn-primary btn-flat" })
                @Html.RouteLink("Удалить", "happiness_delete", new { happinessId = x.HappinessId }, new { @class = "btn btn-danger btn-flat" })
            </div>);
    })

    <a class="btn btn-link" href="@Url.RouteUrl("happiness_create")">Создать</a>
</div>